### PR TITLE
Add shiny text explanation

### PR DESCRIPTION
**Pull request by pommedeterresautee**
* Add interactive text explanation
* text explanations plot functions keeps original formating (new line, ...) + add info on the prediction

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
@thomasp85 do we want to unit test Shiny ? Seems difficult (package not on Cran, ...)

**Comment by thomasp85** [comment]
Don't think we should unit test shiny at this moment...

**Comment by pommedeterresautee** [comment]
Just an idea, can you merge the whole list of commits so in the PR only the new commits appear? (instead of squash)
(I know it will add many commits not very interesting, but very few people will look at the past, and I hope, you will have several occasions to review my PRs)

**Comment by pommedeterresautee** [comment]
@thomasp85 I share your opinion about testing shiny, we can wait for the testing frameworks to be more mature before implementing tests.

**Comment by thomasp85** [comment]
I'd rather squash, and then you make a new branch every time a new feature gets developed. That way you don't have to deal with merging my master into your master if they have diverged

**Pull request merged**
