### PR TITLE
changed names() to colnames()

### PR DESCRIPTION
**Pull request by millerjoey**
Also, y is case_res and is a matrix, so I access it with y[, label], not y[[label]].

### CODE REVIEW

**Comment by millerjoey** [comment]
Yes, it works with caret and I just noticed why. In my testing, I didn't
use caret--tested on random forest and some of my own models.

When you predict (type = "probs") on a model trained by caret, the names
attribute contains the colnames (this I didn't know), so it doesn't cause
any trouble. But if you try doing:

library(lime)

iris_test <- iris[1:5, 1:4]
iris_train <- iris[-(1:5), 1:4]
iris_lab <- iris[[5]][-(1:5)]

model <- randomForest::randomForest(iris_train, iris_lab)
explain <- lime(iris_train, model)
explanation <- explain(iris_test, n_labels = 1, n_features = 2)
plot_features(explanation)

# See here, no names attribute, but colnames works.
preds <- predict(model, iris_test, type = "prob")
names(preds)
colnames(preds)

Without my changes, you should get an error.

**Comment by pommedeterresautee** [comment]
IMHO the issue is related to the Lime API. 
We can't expect everybody will use caret.
The user should provide to LIME a function which takes the permutations and return the predictions as a DF. Lime would just check the type of the return.
It would replace the model argument and the preprocess argument.

**Comment by thomasp85** [comment]
The big problem is that there are hundreds of models that all have their different return values. The reason for the caret (and now mlr) focus is to avoid having to deal with all these things when other people have done it already. There will soon come a way to supply your own predict wrapper if you insist on foregoing caret/mlr

**Comment by millerjoey** [comment]
Just to be clear: using colnames() will work with caret (which looks like
it returns a data.frame, so no surprise that names() gets the colnames).
The nice thing is that it will also work with predict methods that return
matrices. Tibbles will break it though..

So yeah, might be simpler to only support caret or mlr in the future, but
this particular suggestion doesn't cause any problems afaik.

**Comment by thomasp85** [comment]
`colnames` can stay, but I think that rather than use `[, label]` we should put in an `y <- as.data.frame(y)` in the beginning to make sure that it works with tibbles

If you change this I'll merge

**Comment by millerjoey** [comment]
It looks like it's been merged. But if you want it to work with tibbles, I
think a better approach might be to just

case_res <- as.tibble(predict(model, case_perm, type = "prob"))

Sound better?

**Comment by millerjoey** [comment]
It should turn the matrix's colnames() into the names() of the tibble, so
no other changes are needed.

**Pull request closed without merging**
